name: Build

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        package:
          - default
          - rust
      fail-fast: true
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: sestrella
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          skipPush: ${{ github.ref_name != 'main' }}
      - run: nix build .#${{ matrix.package }}
      - run: nix run .#${{ matrix.package }} -- --version

  template:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - run: nix profile add nixpkgs#devenv
      - run: sed -i 's/github:sestrella\/auto-commit-msg/github:sestrella\/auto-commit-msg?ref=${{ github.sha }}/g' templates/default/devenv.yaml
      - run: echo "tmpdir=$(mktemp -d)" >> "$GITHUB_OUTPUT"
        id: mktemp
      - run: git init
        working-directory: ${{ steps.mktemp.outputs.tmpdir }}
      - run: nix flake init -t ${{ github.workspace }}
        working-directory: ${{ steps.mktemp.outputs.tmpdir }}
      - run: devenv test
        working-directory: ${{ steps.mktemp.outputs.tmpdir }}
